### ISSUE TITLE
Auto-accept post corrections/accept default symptoms chips in ROS

### ISSUE THREAD

**Issue by lukesmurray** [lukesmurray/bidmc-ml-ui#138]
This can be abstracted as auto-accepting post-corrections for certain phrases/sections like ROS.

Need to also augment metrics with this information by specifying whether a chip was added an an auto-accepted post correction or whether it was manually selected.

**Comment by lukesmurray** [comment]
This is in progress on #205 

currently implemented as part of the post recognition decorator. The component for post recognitions gets the suggestions associated with the post recognition and if the suggestions pass certain heuristics then the post recognition is rendered as a suggestion chip. Since one of the heuristics is that there is only one possible suggestion that single suggestion is the suggestion chip.

- known bugs

All other chips are implemented as entities, since these chips are not entities they do not appear in any of the current code which finds suggestions using the entity type. An example is auto scopes are failing due to this code not picking up the auto recognized chips https://github.com/lukesmurray/bidmc-ml-ui/blob/436df97e01249ebdca6f781e010ad0927ab635e9/src/components/plugins/suggestions/decorators/suggestionPortalStrategy.ts#L765-L784.

Another example is the way we pick up suggestions in the store. https://github.com/lukesmurray/bidmc-ml-ui/blob/436df97e01249ebdca6f781e010ad0927ab635e9/src/store/suggestions/suggestionChips.ts#L131-L191 These suggestions are used in the sidebar so we do need to pick them up correctly.

Haven't come up with a solution for these. But some ideas

- extract decorators instead of entities
  - not supported by draft js, decorator's don't have keys associated with them as far as I'm aware

**Comment by divya-gopinath** [comment]
Some bugs:
- [ ] Need autocomplete dropdown to appear after automatically-added post-corrections.
- [ ] Dropdown to accept post corrections should be richer. As an example, typing `diabetes` as a post-correction gives a dropdown with two identical entries (I'm guessing they map to different common names) . This is especially problematic with labs because we don't display fluid type in the post correction dropdown. 
- [ ]  Might want to auto-accept post-corrections even _with_ a collision if they appear directly after an autoscope token. E.g. `h/o chest pain` indicates we want the HPI version, not symptoms. We could also add this behavior on a section level, e.g. any collision in ROS is automatically a symptom unless it comes directly after an autoscope section. Would also be helpful for MED, PMH sections (right now, many of the post corrections in Meds are terms like `Lidocaine` which are also labs but based on the section we can infer the term type almost deterministically). 
- [ ] Default text prior to a colon should never be post-corrected. As an example, `Location:` in HPI is post-corrected even though it's not a medical term. We could also avoid fixing this until we implement tabbed forms as in issue https://github.com/lukesmurray/bidmc-ml-ui/issues/140
